# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Comment.destroy_all
Message.destroy_all
Following.destroy_all
Species.destroy_all
User.destroy_all

u1=User.create(username:"abril", password:"abc123")
u2=User.create(username:"gia", password:"abc123")
u3=User.create(username:"kevin", password:"abc123")

s1=Species.create(common_name:"Polar Bear", scientific_name:"ursus maritimus", habitat:"artic sea ice", population:"22,000-31,000", threat_type:"Vulnerable", use_trade:"Many Arctic areas have strong polar bear management and monitoring. But there are a few places where unsustainable hunting appears to be happening, including unreported and illegal hunting.", conservation_measure:"Supporting community projects in Alaska and Russia to prevent unintended and potentially fatal encounters between polar bears and people. Local polar bear patrol teams help keep towns and bears safe. Better lighting near public places, electric fencing, bear-proof food storage containers and warning plans for when bears enter communities all help reduce conflict.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOuAvU-GqohRSYc7zzZiGv1xOhX0bzNfYxdA67kQ6Vai1TUtAXBg", group:"Mammals")

s2=Species.create(common_name:"Blue Whale", scientific_name:"balaenoptera musculus", habitat:"oceans", population:"10,000-25,000 individuals", threat_type:"Endangered", use_trade:"commercial whaling", conservation_measure:"Since the introduction of the whaling ban, studies have examined whether the conservation reliant global blue whale population is increasing or remaining stable. In the Antarctic, best estimates show an increase of 7.3% per year since the end of illegal Soviet whaling, but numbers remain at under 1% of their original levels.Recovery varies regionally, and the Eastern North Pacific blue whale population (historically a relatively small proportion of the global total) has rebounded to about 2,200 individuals, an estimated 97% of its pre-hunting population.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr-VKRMvWQio3PJD0h-Eughe8cL0PtvPcbKPm76KyNzcOYaDHZAw", group:"Mammals")

s3=Species.create(common_name:"Orangutan", scientific_name:"pongo abelii", habitat:"forest habitat", population:"about 104,700 (Bornean), 13,846 (Sumatran), 800 (Tapanuli)", threat_type:"Critically Endangered", use_trade:"Females are hunted most often. When caught with offspring, the young are often kept as pets. The pet trade is a major problem. It is thought that for each orangutan reaching Taiwan, as many as 3-5 additional animals die in the process. Recent enforcement of the law in Taiwan has reduced the importation of orangutans, but the trade remains a threat in Indonesia where there is still demand for orangutans as pets. There is also trade in orangutan skulls in Kalimantan (Indonesian Borneo).", conservation_measure:"Conserving orangutan habitat, antipoaching, promoting sustainable forestry and agriculture, and halting the pet trade. The habitats of Asia's only great apes are fast disappearing under the chainsaw to make way for oil palm plantations and other agricultural plantations. Illegal logging inside protected areas and unsustainable logging in concessions where orangutans live remains a major threat to their survival. Today, more than 50% of orangutans are found outside protected areas in forests under management by timber, palm oil and mining companies.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9tgXBVEilr1NnJR9KLrhKJ26wVjDNI2Y7kjgfwsJWEVi_61zgqw", group:"Primates")

s4=Species.create(common_name:"Tiger", scientific_name:"panthera tigris", habitat:"Tropical rainforests, evergreen forests, temperate forests, mangrove swamps, grasslands and savannas", population:"Around 3,900", threat_type:"Endangered", use_trade:"Poaching is the most immediate threat to wild tigers. Every part of the tiger—from whisker to tail—is traded in illegal wildlife markets. A result of persistent demand, their bones and other body parts are used for modern health tonics and folk remedies, and their skins are sought after as status symbols among some Asian cultures.", conservation_measure:"Tigers need landscapes to thrive, and our work to protect and connect their fragile habitat is based on rigorous scientific analysis. WWF has chosen places to focus its resources based on the best available science. These areas are where densities of prey and tigers are at their highest. The locations encompass tiger corridors that link tiger sites within landscapes. Our work includes building local capacity to manage protected areas, coordinating with partners to manage core tiger areas and corridors, and addressing human-wildlife conflict and the impacts of infrastructure development in tiger landscapes.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/2090/images/featured_story/Sumatran-Tiger-Hero.jpg?1345559303", group:"Big Cats")

s5=Species.create(common_name:"Sea Turtle", scientific_name:"Cheloniidae and Dermochelyidae families", habitat:"Open water and coasts", population:"Unknown", threat_type:"Vulnerable", use_trade:"Used for human and trade of their parts. Also killing turtles for medicine and religious ceremonies.", conservation_measure:"Establishing  marine protected  areas, ensuring sea turtles have a safe place to nest, feed and migrate freely. The WWF supports local turtle conservationists in many parts of the world to monitor and patrol turtle nests.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ-5Kytje_a9J9CUSR_FlLRGW770GdDxt2o_FJr2mShTruwVXf", group:"Marine Animals")

s6=Species.create(common_name:"Gorilla", scientific_name:"Gorilla gorilla and Gorilla beringei", habitat:"artic sea ice", population:"100,000 to 200,000", threat_type:"Critically Endangered", use_trade:"Gorillas are completely protected by national and international laws in all countries of their range, and it is, therefore, illegal to kill, capture or trade in live Gorillas or their body parts.Although in some cultures in central Africa, the killing and eating of gorillas has increased in recent years and the animals are frequently slaughtered for the bushmeat trade.", conservation_measure:"DEVELOPING TOURISM
Ecotourism provides opportunities for protecting gorillas and their forest homes and for helping the local people. WWF has habituated gorilla groups to humans to develop opportunities for gorilla tourism. Monitoring population. Preserving Habitat: Habitat destruction is a concern for all four gorilla subspecies. WWF has worked to designate new protected areas for gorillas in many places, like in Cameroon, where gorilla sanctuaries would provide havens for the rare cross river gorilla as well as the western lowland gorilla.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1102/images/featured_story/Gorillas_7.31.2012_Our_closest_cousins_HI_105193.jpg?1345537507", group:"Primates")

s7=Species.create(common_name:"Jaguar", scientific_name:"Panthera onca", habitat:"Forests, Grasslands", population:"Current popolation trend is decreasing", threat_type:"Near Threatened", use_trade:"Wearing apparel and accessories.There is still demand for Jaguar paws, teeth and other products, especially in local markets where canines are still considered interesting jewellery. On top of this, Jaguars are starting to be considered a replacement for tiger bone for traditional medicine purposes by the increasing Asian community in Latin America.", conservation_measure:"Conducting an exhaustive synthesis of all known jaguar observations in the northern part of its range since the 16th Century. The accuracy, precision, and reliability of observations over such a long period of history vary, so WCS built a novel database structure to account for the types of criteria team members might use to include or exclude observations from consideration.The WCS Jaguar Conservation Program worked with a group of scientists from within and outside WCS to create an authoritative guide on jaguar survey and monitoring techniques and methodologies relevant to the northern part of their range. ", image:"https://c402277.ssl.cf1.rackcdn.com/photos/2572/images/featured_story/GPN7474_Amazon_jaguar.jpg?1349186039", group:"Big Cats")

s8=Species.create(common_name:"Great White Shark", scientific_name:"Carcharodon carcharias", habitat:"Oceans", population:"With fossil records dating back 400 million years, sharks have outlived the dinosaurs and many other forms of life currently on earth. There are more than 1,000 species of sharks and rays, with new species discovered every year.", threat_type:"Vulnerable", use_trade:" Protective laws are strict, but loopholes and inadequate enforcement causes problems including promoting the black-market for high-value Great White Shark products including jaws, teeth and fins", conservation_measure:"These majestic top predators that are so essential to the natural order of marine ecosystems now face their most severe threat from overfishing. Many species are threatened with extinction, with some families of rays such as sawfishes in peril. While sharks and rays have been an irreplaceable resource for coastal communities in the developing world for centuries, this unique balance is in danger of being lost forever. With our oceans severely degraded, restoring sharks is key to improving the resilience of these water bodies to climate change. While sharks' diverse range of species adds complexity to our conservation efforts, the dwindling numbers of these amazing creatures from overfishing and demand for their fins and meat increases the urgency of the task. The Great White Shark was added to both Appendices of the Convention on the Conservation of Migratory Species (CMS) in 2002 with the objective of providing a framework for the coordination of measures adopted by range states to improve the conservation of the species (Government of Australia 2002). The great white shark should be removed from international game fish record lists, and needs consistently rational and realistic treatment by entertainment and news media to counter its notoriety and inflated market value.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1088/images/featured_story/great_white_shark_7.30.2012_whytheymatter_HI_111754.jpg?1436194707", group:"Marine Animals")

s9=Species.create(common_name:"Giant Pandas", scientific_name:"Ailuropoda melanoleuca", habitat:"Temperate broadleaf and mixed forests of southwest China", population:"1,864 in the wild", threat_type:"Vulnerable", use_trade:"Although historically the Giant Panda was sometimes hunted for its pelt, law enforcement mechanisms appear to have eliminated this trade.", conservation_measure:"The primary threat facing Giant Panda populations is the continuing effects of previous habitat loss, resulting in highly fragmented habitat and, in many cases small, isolated populations. The Giant Panda has been the focus of one of the most intensive, high profile efforts to recover an endangered species. In 1981, China joined the Convention on the International Trade in Endangered Species (CITES), which made trade of Panda skins illegal. Ecocompensation has been proposed as an important component of a conservation strategy for pandas (Yang et al. 2013, 2015; Liu et al. 2008, 2015; Tuanmu et al. 2015). Approximately 15% of the remaining unprotected habitat occurs in collectively-owned forests. Payment for ecosystem services, which has already been shown to benefit Panda conservation under the Grain-to-Green Program, could extend conservation measures into these unprotected areas.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/479/images/featured_story/giant-panda-shutterstock_86500690.jpg?1345572346", group:"Mammals")

s10=Species.create(common_name:"Javan Rhinoceros", scientific_name:"Rhinoceros sondaicus", habitat:"Tropical and subtropical grasslands, savannahs and shrublands, tropical moist forests, deserts and xeric shrublands", population:"58-68", threat_type:"Critically Endangered", use_trade:"Over-hunting for its horn and other medicinal products has driven this formerly widespread species to the brink of extinction.", conservation_measure:"Natural disaster, Poaching and disease are the biggest threats. To reduce the likelihood of extinction in the event of a major natural disaster in Ujung Kulon National Park, WWF and partners are working to establish a second population of Javan rhinos.Effective protection of the world’s only remaining Javan rhino population is critical to ensuring the species’ survival. WWF will continue our support for rhino protection patrols in Ujung Kulon National Park and work with communities who live in the park’s buffer zone to eliminate human encroachment into the Javan rhino’s limited habitat and poaching.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQkenKH7k5A7lYpX-gukIawzYgzvH6c7CW4le65J3U0vFNccIw", group:"Mammals")

s11=Species.create(common_name:"Asian Elephant", scientific_name:"Elephas maximus indicus", habitat:"Forests", population:"Fewer than 50,000", threat_type:"Endangered", use_trade:"Even where suitable habitat exists, poaching remains a threat to elephants in many areas. In 1989, the Convention on International Trade in Endangered Species of Wild Fauna and Flora (CITES) banned the international trade in ivory. However, there are still some thriving but unregulated domestic ivory markets in a number of countries which fuel an illegal international trade. Although most of this ivory comes from poaching of African elephants, Asian elephants are also illegally hunted for their ivory, as well as for their skin. In some countries, political unrest is disrupting antipoaching activities.", conservation_measure:"The main threat facing Indian elephants, like all Asian elephants is loss of habitat, which then results in human-elephant conflict. In South Asia, an ever-increasing human population has led to many illegal encroachments in elephant habitat. Many infrastructure developments like roads and railway tracks also fragment habitat. Protecting Elephant Habitat: In the Terai Arc Landscape, which encompasses parts of western Nepal and eastern India, WWF and its partners restore degraded biological corridors so that elephants can access their migratory routes without disturbing human habitations. The long-term goal is to reconnect 12 protected areas and encourage community-based action to mitigate human-elephant conflict. Such approaches are being facilitated by WWF across the range of the Indian elephant.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1732/images/featured_story/Asian_Elephant_8.13.2012_Hero_And_Circle_HI_247511.jpg?1345551842", group:"Mammals")

s12=Species.create(common_name:"Chimpanzee", scientific_name:"Pan troglodytes", habitat:"Forests (moist and dry forests", population:"172,700 to 299,700", threat_type:"Endangered", use_trade:"Poaching is another prominent threat. Bushmeat has always been a primary food source in Central and West Africa, but in recent years poaching has become commercialized to satisfy the appetites of wealthy urban residents. Infant chimpanzees are frequently taken alive and sold in cities as pets. Disease stalks chimpanzees: Ebola outbreaks have killed tens of thousands of great apes.", conservation_measure:"Develop chimpanzee-focused ecotourism and work to stop illegal poaching in logging concessions. WWF continues to look for ways to reduce the impact of the bushmeat trade on apes and other endangered species. The WWF establishes, strengthens, and manages protected areas in Central and West Africa. In Democratic Republic of Congo, the Central African Republic, Gabon, Cameroon and other countries: protect chimpanzees through antipoaching and effective law enforcement, help governments establish and manage national parks, monitor chimpanzee populations, encourage sustainable use of forest resources in park buffer zones, and build trans-boundary collaboration to develop partnerships between neighboring countries.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1255/images/featured_story/Chimpanzee-1600x600px.jpg?1345590038", group:"Primates")

s13=Species.create(common_name:"Brown Bear", scientific_name:"Ursus arctos", habitat:"Forests, Tundra", population:"110,000", threat_type:"Least Concern", use_trade:"Brown bears were pursued extensively due to their size, valuable furs and meat. The brown bear population now occupies just 2% of its former range. Bear gall bladders reportedly bring high prices as traditional medicines on the Asian market although there is no evidence that products derived from bear parts have medical value.", conservation_measure:"Human expansion into the bears’ natural habitat, as well as instances where brown bears are considered nuisances, demonstrate the tension that exists between bears and people. Logging, mining, road construction, and other development—coupled with human attempts to prevent brown bears’ interference with things like livestock, crops, water supplies, and garbage bins—all impact this animal population. Conservation actions for Brown Bears vary greatly among nations and regions within nations. Large populations of this species (in Russia, Japan, Canada, Alaska, and parts of eastern and northern Europe) are legally hunted, and thus managed as a game animal. Hunting regulations, usually designed to ensure a sustainable harvest of bears, vary among areas but often involve a lottery for a limited number of permits (a quota system) and restricted season length. Most small populations are protected by national laws and international agreements, with varying degrees of enforcement. Brown Bear as a species is listed under CITES Appendix II", image:"https://c402277.ssl.cf1.rackcdn.com/photos/6121/images/featured_story/MID_58378.jpg?1389813140", group:"Mammals")

s14=Species.create(common_name:"Sea Lions", scientific_name:"Zalophus wollebaeki", habitat:"Oceans. The sea lion is the most common mammal in the Galápagos.", population:"22,000-31,000", threat_type:"Endangered", use_trade:"Whalers and sealers harvested Galápagos Fur Seals indiscriminately during the 19th century and there were few left by 1900. The population recovered substantially during the 20th century. Galápagos Fur Seals were protected under Ecuadorian law in the 1930s, and since 1959 with the establishment of the Galápagos National Park, by the Administration of the Park. Currently there is no direct use or trade.", conservation_measure:"Introduced species, such as dogs, carry diseases that can spread to sea lions. They are vulnerable to the effects of climate change on ocean currents, which impacts their fish prey abundance. They are also victims of bycatch in fisheries. Sea lions often rest aboard fishing boats, sometimes causing the boats to sink. Fishermen try to prevent them from coming aboard by putting up barbwire as a barrier, but this causes severe injuries to the sea lions. WWF helped support a project on San Cristóbal Island that built and installed two floating bases for sea lions to rest on and a “primary care nursery” for sea lions and other species. Currently, sea lions are using the floating bases more often and we expect less sea lion injuries and fewer troubles for the boat owners on the island.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/560/images/featured_story/sea-lion-07162012-hero-shutterstock_90483844.jpg?1345525771", group:"Marine Animals")

s15=Species.create(common_name:"Snow Leopard", scientific_name:"Panthera uncia", habitat:"cold high mountains", population:"total estimated 4,080-6,590", threat_type:"Vulnerable", use_trade:"Snow leopards are often killed by local farmers because they prey on livestock such as sheep, goats, horses, and yak calves. The animals which snow leopards would typically hunt—such as the Argali sheep—are also hunted by local communities. As their natural prey becomes harder to find, snow leopards are forced to kill livestock for survival.", conservation_measure:" Conservation initiatives that blend conservation science with traditional knowledge, and which mitigate Snow Leopard-related human-wildlife conflict, improve household incomes for households dependent upon livestock, and that highlight the cultural and ecological importance of Snow Leopards are also most likely to be embraced by local people who likely represent the effective and cost-efficient stewards for this felid's remote mountain landscapes (Jackson and Brewer-Lama 2016).", image:"https://c402277.ssl.cf1.rackcdn.com/photos/481/images/featured_story/snowleopardXL_257721.jpg?1345572455", group:"Big Cats")

s16=Species.create(common_name:"Artic Fox", scientific_name:"Vulpes lagopus", habitat:"Tundra", population:"Several hundred thousand", threat_type:"Least Concern", use_trade:"Many Arctic areas have strong polar bear management and monitoring. But there are a few places where unsustainable hunting appears to be happening, including unreported and illegal hunting.", conservation_measure:"The scarcity of prey is the most prevalent threat for the Arctic fox. Disease and genetic pollution of the species by foxes bred in captivity also threatens this species. Protectic and supporting fragile ecosystems and mitigating the effects of climate change to ensure the survival of the Arctic fox and other species.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/540/images/featured_story/shutterstock_103864847.jpg?1345525295", group:"Mammals")

s17=Species.create(common_name:"Bluefin Tuna", scientific_name:"Thunnus Thynnus", habitat:"Oceans", population:"", threat_type:"Endangered", use_trade:"The Atlantic bluefin is a highly sought-after delicacy for sushi and sashimi in Asia—a single fish has sold for over $1.75 million! Driven by such high prices, fishermen use even more refined techniques to catch tuna. And the fish are disappearing as a result. Although tuna do provide food and livelihoods for people, they are more than just seafood. Tuna are a top predator in the marine food chain, maintaining a balance in the ocean environment.", conservation_measure:"In the Mediterranean, WWF has been working for over 10 years to protect Atlantic bluefin tuna. We work to stop overfishing and ensure recovery of the Eastern Atlantic and Mediterranean stock. WWF has been very influential in most of the decisions made by the International Commission for the Conservation of Atlantic Tunas (ICCAT), the body that regulates the fisheries.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/2110/images/featured_story/Bluefin-Tuna-Hero.jpg?1345559603", group:"Marine Animals")

s18=Species.create(common_name:"Black-footed Ferret", scientific_name:"Mustela nigripes", habitat:"Grasslands", population:"Approximately 370 in the wild", threat_type:"Endangered", use_trade:"This species is not used", conservation_measure:"Habitat loss and non-native disease threaten the recovery of the black-footed ferret. The ferret is entirely dependent on the presence of prairie dogs and their colonies for food, shelter and raising young. Without ample reintroduction sites and protection from plague, full black-footed ferret recovery remains difficult. Beginning in 1985, more than 8,000 Black-footed Ferrets have been born in captivity, with 323 kits weaned in 2014. Beginning in 1991, Ferrets have been reintroduced at sites in eight Western U.S. states (Montana, South Dakota, Wyoming, Colorado, Utah, Arizona, Kansas and New Mexico), one site in Mexico (Bard 2002, Bronson et al. 2007) and one site in Canada. In 2014 alone, 202 kits were released at nine separate reintroduction sites. The species is listed on CITES Appendix I and is listed under the U.S. Endangered Species Act.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/393/images/featured_story/WEB_202562.jpg?1345570463", group:"Mammals")

s19=Species.create(common_name:"Black Rhino", scientific_name:"Diceros bicornis", habitat:"Semi-Desert Savannah, Woodlands, Forests, Wetlands", population:"22,000-31,000", threat_type:"Critically Endangered", use_trade:"Of all the threats facing black rhinos, poaching is the deadliest. Black rhinos have two horns which make them lucrative targets for the illegal trade in rhino horn A wave of poaching for rhino horn rippled through Kenya and Tanzania, continued south through Zambia's Luangwa Valley as far as the Zambezi River, and spread into Zimbabwe.", conservation_measure:"Thanks to persistent conservation efforts across Africa, black rhino numbers have doubled from their historic low 20 years ago to between 5,042 and 5,455 today. However, the black rhino is still considered critically endangered, and a lot of work remains to bring the numbers up to even a fraction of what it once was—and to ensure that it stays there. Rhinos are one of the oldest groups of mammals, virtually living fossils. They play an important role in their habitats and in countries like Namibia, rhinos are an important source of income from ecotourism. The protection of black rhinos creates large blocks of land for conservation purposes. This benefits many other species, including elephants.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1382/images/featured_story/Black_Rhino_8.6.2012_Why_they_matter_HI_204737.jpg?1345543817", group:"Mammals")

s20=Species.create(common_name:"Tasmanian Tiger", scientific_name:"Thylacinus cynocephalus", habitat:"Forest, Grassland", population:"---", threat_type:"Extinct", use_trade:"---", conservation_measure:"In 1936, the Thylacine received legal protection under Tasmanian law, although it was probably already extinct (Mooney and Rounsevell 2008). In 1966, a 647,000 ha game reserve was set up in south-western Tasmania, partly to protect any animals possibly remaining in the area. Currently there are no conservation measures pertaining to this species as it is presumed extinct. It is listed on CITES Appendix I.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb3z_qbNglBvcYKC440rCfCZPmY2LeQL_sDn0RNTl8UAgh8eiK", group:"Marsupial")

s21=Species.create(common_name:"Spix's macaw", scientific_name:"Cyanopsitta spixii", habitat:"Forest, Shrubland", population:"1-49", threat_type:"Critically Endangered", use_trade:"Food and as pets or display animals", conservation_measure:"Identify a suitable release site for the potential annual release of captive-bred birds starting between 2013 and 2030 depending on the success of captive breeding efforts (de Soye and de Melo Barros 2006). Continue to develop artificial reproduction techniques to boost the population. Protect and improve habitat at the identified release site (de Soye and de Melo Barros 2006). Establish a well-resourced on site reintroduction facility at Praia do Forte under IBAMA ownership (de Soye and de Melo Barros 2006). Introduce captive-bred fledglings and ensure protection from trappers. Continue cooperation between holders of captive birds. Continue ecological studies to assess the need for habitat management (Snyder et al. 2000). Continue the community programmes.", image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Cyanopsitta_spixii_-Vogelpark_Walsrode%2C_Walsrode%2C_Germany-1980.jpg/440px-Cyanopsitta_spixii_-Vogelpark_Walsrode%2C_Walsrode%2C_Germany-1980.jpg", group:"Birds")

s22=Species.create(common_name:"Alagoas Curassow", scientific_name:"Mitu mitu", habitat:"Forest", population:"---", threat_type:"Extinct in the Wild", use_trade:"---", conservation_measure:"A private captive population, supplemented from the wild, was established in 1977, and divided between two well known aviculturists in 1999 when it numbered 44 individuals, with 10 eggs in artificial incubation (Atualidades Ornitológicas 2000). A 30 km2 forest remnant in Alagoas (Reserva Particular do Patrimonio Natural Mata do Cedro) has been identified for potential reintroduction attempts by the government of Alagoas (Grau et al. 2003, Gama et al. 2016). In autumn 2017, the first two individuals were transferred to a 400 m2 aviary in Mata do Cedros to adapt to the reintroduction site. The reintroduction is scheduled to start in 2018 (Lisboa 2017). Other efforts in 1983-1985 to capture wild individuals for a captive-breeding population failed. Searches of remaining forest fragments in 2001 failed to find any trace of the species (Silveira et al. 2003). ", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFVKzRNsWbbTqLyuBvO7-9II8eHN8DTY8S7LmAqcw-eAozNFZo", group:"Birds")

s1=Species.create(common_name:"Père David's Deer", scientific_name:"Elaphurus davidianus", habitat:"Wetlands (inland), Marine Intertidal, Grassland", population:"Unspecified", threat_type:"Extinct in the Wild", use_trade:"---", conservation_measure:"t is listed on the Chinese Red List as Extinct in the Wild, and on the China Key List - I. Recommended conservation action includes:
1. Establish additional populations when and where appropriate, with the aim of re-establishing a genuinely wild, free-ranging population.
2. Conduct surveys of the four free-living sub-populations in Hubei and Hunan provinces to assess their long-term viability.
3. Establish a genetic management programme of all populations in China.
4. Develop conservation education programmes to raise conservation awareness among the local people and general public.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5BdZPhKvjlDrga9BMDLSzuASQC32TXqaBIKKVuUVah20WV0Sa", group:"Mammals")






   


















f1=Following.create(user:u2, species:s1)
f2=Following.create(user:u3, species:s1)
f3=Following.create(user:u2, species:s2)


c1=Comment.create(user:u1, species:s2, content:"I want to travel the world and go to the best whale watching tours, any suggestions?")
c2=Comment.create(user:u2, species:s3, content:"Awww")

# m1=Message.create(following:f1, maker:u1, receiver:u2, content:"Hello! I love the polar bear too")
# m2=Message.create(following:f2, maker:u1, receiver:u3, content:"Cute")
# m3=Message.create(following:f3, maker:u1, receiver:u2, content:"Hello! Whales are the best!!")
