# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Comment.destroy_all
Message.destroy_all
Following.destroy_all
Species.destroy_all
User.destroy_all

u1=User.create(username:"abril", password:"abc123")
u2=User.create(username:"gia", password:"abc123")
u3=User.create(username:"kevin", password:"abc123")

s1=Species.create(common_name:"Polar Bear", scientific_name:"ursus maritimus", habitat:"artic sea ice", population:"22,000-31,000", threat_type:"Vulnerable", use_trade:"unknown", conservation_measure:"Supporting community projects in Alaska and Russia to prevent unintended and potentially fatal encounters between polar bears and people. Local polar bear patrol teams help keep towns and bears safe. Better lighting near public places, electric fencing, bear-proof food storage containers and warning plans for when bears enter communities all help reduce conflict.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOuAvU-GqohRSYc7zzZiGv1xOhX0bzNfYxdA67kQ6Vai1TUtAXBg", group:"Mammals")

s2=Species.create(common_name:"Blue Whale", scientific_name:"balaenoptera musculus", habitat:"oceans", population:"10,000-25,000 individuals", threat_type:"Endangered", use_trade:"commercial whaling", conservation_measure:"Since the introduction of the whaling ban, studies have examined whether the conservation reliant global blue whale population is increasing or remaining stable. In the Antarctic, best estimates show an increase of 7.3% per year since the end of illegal Soviet whaling, but numbers remain at under 1% of their original levels.Recovery varies regionally, and the Eastern North Pacific blue whale population (historically a relatively small proportion of the global total) has rebounded to about 2,200 individuals, an estimated 97% of its pre-hunting population.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr-VKRMvWQio3PJD0h-Eughe8cL0PtvPcbKPm76KyNzcOYaDHZAw", group:"Mammals")

s3=Species.create(common_name:"Orangutan", scientific_name:"pongo abelii", habitat:"forest habitat", population:"about 104,700 (Bornean), 13,846 (Sumatran), 800 (Tapanuli)", threat_type:"Critically Endangered", use_trade:"Females are hunted most often. When caught with offspring, the young are often kept as pets. The pet trade is a major problem. It is thought that for each orangutan reaching Taiwan, as many as 3-5 additional animals die in the process. Recent enforcement of the law in Taiwan has reduced the importation of orangutans, but the trade remains a threat in Indonesia where there is still demand for orangutans as pets. There is also trade in orangutan skulls in Kalimantan (Indonesian Borneo).", conservation_measure:"Conserving orangutan habitat, antipoaching, promoting sustainable forestry and agriculture, and halting the pet trade. The habitats of Asia's only great apes are fast disappearing under the chainsaw to make way for oil palm plantations and other agricultural plantations. Illegal logging inside protected areas and unsustainable logging in concessions where orangutans live remains a major threat to their survival. Today, more than 50% of orangutans are found outside protected areas in forests under management by timber, palm oil and mining companies.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9tgXBVEilr1NnJR9KLrhKJ26wVjDNI2Y7kjgfwsJWEVi_61zgqw", group:"Primates")

s4=Species.create(common_name:"Tiger", scientific_name:"panthera tigris", habitat:"Tropical rainforests, evergreen forests, temperate forests, mangrove swamps, grasslands and savannas", population:"Around 3,900", threat_type:"Endangered", use_trade:"Poaching is the most immediate threat to wild tigers. Every part of the tiger—from whisker to tail—is traded in illegal wildlife markets. A result of persistent demand, their bones and other body parts are used for modern health tonics and folk remedies, and their skins are sought after as status symbols among some Asian cultures.", conservation_measure:"Tigers need landscapes to thrive, and our work to protect and connect their fragile habitat is based on rigorous scientific analysis. WWF has chosen places to focus its resources based on the best available science. These areas are where densities of prey and tigers are at their highest. The locations encompass tiger corridors that link tiger sites within landscapes. Our work includes building local capacity to manage protected areas, coordinating with partners to manage core tiger areas and corridors, and addressing human-wildlife conflict and the impacts of infrastructure development in tiger landscapes.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/2090/images/featured_story/Sumatran-Tiger-Hero.jpg?1345559303", group:"Big Cats")

s5=Species.create(common_name:"Sea Turtle", scientific_name:"Cheloniidae and Dermochelyidae families", habitat:"Open water and coasts", population:"Unknown", threat_type:"Vulnerable", use_trade:"Used for human and trade of their parts. Also killing turtles for medicine and religious ceremonies.", conservation_measure:"Establishing  marine protected  areas, ensuring sea turtles have a safe place to nest, feed and migrate freely. The WWF supports local turtle conservationists in many parts of the world to monitor and patrol turtle nests.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ-5Kytje_a9J9CUSR_FlLRGW770GdDxt2o_FJr2mShTruwVXf", group:"Marine Animals")

s6=Species.create(common_name:"Gorilla", scientific_name:"Gorilla gorilla and Gorilla beringei", habitat:"artic sea ice", population:"100,000 to 200,000", threat_type:"Critically Endangered", use_trade:"Gorillas are completely protected by national and international laws in all countries of their range, and it is, therefore, illegal to kill, capture or trade in live Gorillas or their body parts.Although in some cultures in central Africa, the killing and eating of gorillas has increased in recent years and the animals are frequently slaughtered for the bushmeat trade.", conservation_measure:"DEVELOPING TOURISM
Ecotourism provides opportunities for protecting gorillas and their forest homes and for helping the local people. WWF has habituated gorilla groups to humans to develop opportunities for gorilla tourism. Monitoring population. Preserving Habitat: Habitat destruction is a concern for all four gorilla subspecies. WWF has worked to designate new protected areas for gorillas in many places, like in Cameroon, where gorilla sanctuaries would provide havens for the rare cross river gorilla as well as the western lowland gorilla.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1102/images/featured_story/Gorillas_7.31.2012_Our_closest_cousins_HI_105193.jpg?1345537507", group:"Primates")

s7=Species.create(common_name:"Jaguar", scientific_name:"Panthera onca", habitat:"Forests, Grasslands", population:"Current popolation trend is decreasing", threat_type:"Near Threatened", use_trade:"Wearing apparel and accessories.There is still demand for Jaguar paws, teeth and other products, especially in local markets where canines are still considered interesting jewellery. On top of this, Jaguars are starting to be considered a replacement for tiger bone for traditional medicine purposes by the increasing Asian community in Latin America.", conservation_measure:"Conducting an exhaustive synthesis of all known jaguar observations in the northern part of its range since the 16th Century. The accuracy, precision, and reliability of observations over such a long period of history vary, so WCS built a novel database structure to account for the types of criteria team members might use to include or exclude observations from consideration.The WCS Jaguar Conservation Program worked with a group of scientists from within and outside WCS to create an authoritative guide on jaguar survey and monitoring techniques and methodologies relevant to the northern part of their range. ", image:"https://c402277.ssl.cf1.rackcdn.com/photos/2572/images/featured_story/GPN7474_Amazon_jaguar.jpg?1349186039", group:"Big Cats")

s8=Species.create(common_name:"Great White Shark", scientific_name:"Carcharodon carcharias", habitat:"Oceans", population:"With fossil records dating back 400 million years, sharks have outlived the dinosaurs and many other forms of life currently on earth. There are more than 1,000 species of sharks and rays, with new species discovered every year.", threat_type:"Vulnerable", use_trade:" Protective laws are strict, but loopholes and inadequate enforcement causes problems including promoting the black-market for high-value Great White Shark products including jaws, teeth and fins", conservation_measure:"These majestic top predators that are so essential to the natural order of marine ecosystems now face their most severe threat from overfishing. Many species are threatened with extinction, with some families of rays such as sawfishes in peril. While sharks and rays have been an irreplaceable resource for coastal communities in the developing world for centuries, this unique balance is in danger of being lost forever. With our oceans severely degraded, restoring sharks is key to improving the resilience of these water bodies to climate change. While sharks' diverse range of species adds complexity to our conservation efforts, the dwindling numbers of these amazing creatures from overfishing and demand for their fins and meat increases the urgency of the task. The Great White Shark was added to both Appendices of the Convention on the Conservation of Migratory Species (CMS) in 2002 with the objective of providing a framework for the coordination of measures adopted by range states to improve the conservation of the species (Government of Australia 2002). The great white shark should be removed from international game fish record lists, and needs consistently rational and realistic treatment by entertainment and news media to counter its notoriety and inflated market value.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1088/images/featured_story/great_white_shark_7.30.2012_whytheymatter_HI_111754.jpg?1436194707", group:"Marine Animals")

s9=Species.create(common_name:"Giant Pandas", scientific_name:"Ailuropoda melanoleuca", habitat:"Temperate broadleaf and mixed forests of southwest China", population:"1,864 in the wild", threat_type:"Vulnerable", use_trade:"Although historically the Giant Panda was sometimes hunted for its pelt, law enforcement mechanisms appear to have eliminated this trade.", conservation_measure:"The primary threat facing Giant Panda populations is the continuing effects of previous habitat loss, resulting in highly fragmented habitat and, in many cases small, isolated populations. The Giant Panda has been the focus of one of the most intensive, high profile efforts to recover an endangered species. In 1981, China joined the Convention on the International Trade in Endangered Species (CITES), which made trade of Panda skins illegal. Ecocompensation has been proposed as an important component of a conservation strategy for pandas (Yang et al. 2013, 2015; Liu et al. 2008, 2015; Tuanmu et al. 2015). Approximately 15% of the remaining unprotected habitat occurs in collectively-owned forests. Payment for ecosystem services, which has already been shown to benefit Panda conservation under the Grain-to-Green Program, could extend conservation measures into these unprotected areas.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/479/images/featured_story/giant-panda-shutterstock_86500690.jpg?1345572346", group:"Mammals")

s10=Species.create(common_name:"Javan Rhinoceros", scientific_name:"Rhinoceros sondaicus", habitat:"Tropical and subtropical grasslands, savannahs and shrublands, tropical moist forests, deserts and xeric shrublands", population:"58-68", threat_type:"Critically Endangered", use_trade:"Over-hunting for its horn and other medicinal products has driven this formerly widespread species to the brink of extinction.", conservation_measure:"Natural disaster, Poaching and disease are the biggest threats. To reduce the likelihood of extinction in the event of a major natural disaster in Ujung Kulon National Park, WWF and partners are working to establish a second population of Javan rhinos.Effective protection of the world’s only remaining Javan rhino population is critical to ensuring the species’ survival. WWF will continue our support for rhino protection patrols in Ujung Kulon National Park and work with communities who live in the park’s buffer zone to eliminate human encroachment into the Javan rhino’s limited habitat and poaching.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/9496/images/hero_full/_H9A0249.jpg?1436885827", group:"Mammals")

s11=Species.create(common_name:"Asian Elephant", scientific_name:"Elephas maximus indicus", habitat:"Forests", population:"Fewer than 50,000", threat_type:"Endangered", use_trade:"Even where suitable habitat exists, poaching remains a threat to elephants in many areas. In 1989, the Convention on International Trade in Endangered Species of Wild Fauna and Flora (CITES) banned the international trade in ivory. However, there are still some thriving but unregulated domestic ivory markets in a number of countries which fuel an illegal international trade. Although most of this ivory comes from poaching of African elephants, Asian elephants are also illegally hunted for their ivory, as well as for their skin. In some countries, political unrest is disrupting antipoaching activities.", conservation_measure:"The main threat facing Indian elephants, like all Asian elephants is loss of habitat, which then results in human-elephant conflict. In South Asia, an ever-increasing human population has led to many illegal encroachments in elephant habitat. Many infrastructure developments like roads and railway tracks also fragment habitat. Protecting Elephant Habitat: In the Terai Arc Landscape, which encompasses parts of western Nepal and eastern India, WWF and its partners restore degraded biological corridors so that elephants can access their migratory routes without disturbing human habitations. The long-term goal is to reconnect 12 protected areas and encourage community-based action to mitigate human-elephant conflict. Such approaches are being facilitated by WWF across the range of the Indian elephant.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1732/images/featured_story/Asian_Elephant_8.13.2012_Hero_And_Circle_HI_247511.jpg?1345551842", group:"Mammals")

s12=Species.create(common_name:"Chimpanzee", scientific_name:"Pan troglodytes", habitat:"Forests (moist and dry forests", population:"172,700 to 299,700", threat_type:"Endangered", use_trade:"Poaching is another prominent threat. Bushmeat has always been a primary food source in Central and West Africa, but in recent years poaching has become commercialized to satisfy the appetites of wealthy urban residents. Infant chimpanzees are frequently taken alive and sold in cities as pets. Disease stalks chimpanzees: Ebola outbreaks have killed tens of thousands of great apes.", conservation_measure:"Develop chimpanzee-focused ecotourism and work to stop illegal poaching in logging concessions. WWF continues to look for ways to reduce the impact of the bushmeat trade on apes and other endangered species. The WWF establishes, strengthens, and manages protected areas in Central and West Africa. In Democratic Republic of Congo, the Central African Republic, Gabon, Cameroon and other countries: protect chimpanzees through antipoaching and effective law enforcement, help governments establish and manage national parks, monitor chimpanzee populations, encourage sustainable use of forest resources in park buffer zones, and build trans-boundary collaboration to develop partnerships between neighboring countries.", image:"https://c402277.ssl.cf1.rackcdn.com/photos/1255/images/featured_story/Chimpanzee-1600x600px.jpg?1345590038", group:"Primates")

s13=Species.create(common_name:"Brown Bear", scientific_name:"Ursus arctos", habitat:"Forests, Tundra", population:"110,000", threat_type:"Least Concern", use_trade:"Brown bears were pursued extensively due to their size, valuable furs and meat. The brown bear population now occupies just 2% of its former range. Bear gall bladders reportedly bring high prices as traditional medicines on the Asian market although there is no evidence that products derived from bear parts have medical value.", conservation_measure:"Human expansion into the bears’ natural habitat, as well as instances where brown bears are considered nuisances, demonstrate the tension that exists between bears and people. Logging, mining, road construction, and other development—coupled with human attempts to prevent brown bears’ interference with things like livestock, crops, water supplies, and garbage bins—all impact this animal population. Conservation actions for Brown Bears vary greatly among nations and regions within nations. Large populations of this species (in Russia, Japan, Canada, Alaska, and parts of eastern and northern Europe) are legally hunted, and thus managed as a game animal. Hunting regulations, usually designed to ensure a sustainable harvest of bears, vary among areas but often involve a lottery for a limited number of permits (a quota system) and restricted season length. Most small populations are protected by national laws and international agreements, with varying degrees of enforcement. Brown Bear as a species is listed under CITES Appendix II", image:"https://c402277.ssl.cf1.rackcdn.com/photos/6121/images/featured_story/MID_58378.jpg?1389813140", group:"Mammals")














f1=Following.create(user:u2, species:s1)
f2=Following.create(user:u3, species:s1)
f3=Following.create(user:u2, species:s2)

# m1=Message.create(following:f1, maker:u1, receiver:u2, content:"Hello! I love the polar bear too")
# m2=Message.create(following:f2, maker:u1, receiver:u3, content:"Cute")
# m3=Message.create(following:f3, maker:u1, receiver:u2, content:"Hello! Whales are the best!!")

c1=Comment.create(user:u1, species:s2, content:"I want to travel the world and go to the best whale watching tours, any suggestions?")
c2=Comment.create(user:u2, species:s3, content:"Awww")

